'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PokerHandCalculator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clubs10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clubs10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clubs2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clubs2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clubs3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clubs3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clubs4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clubs4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clubs5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clubs5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clubs6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clubs6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clubs7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clubs7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clubs8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clubs8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clubs9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clubs9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clubsA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clubsA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clubsJ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clubsJ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clubsK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clubsK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clubsQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clubsQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diamonds10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamonds10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diamonds2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamonds2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diamonds3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamonds3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diamonds4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamonds4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diamonds5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamonds5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diamonds6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamonds6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diamonds7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamonds7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diamonds8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamonds8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diamonds9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamonds9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diamondsA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamondsA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diamondsJ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamondsJ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diamondsK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamondsK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property diamondsQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diamondsQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hearts10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hearts10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hearts2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hearts2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hearts3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hearts3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hearts4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hearts4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hearts5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hearts5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hearts6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hearts6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hearts7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hearts7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hearts8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hearts8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hearts9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hearts9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heartsA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartsA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heartsJ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartsJ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heartsK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartsK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heartsQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartsQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spades10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spades10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spades2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spades2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spades3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spades3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spades4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spades4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spades5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spades5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spades6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spades6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spades7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spades7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spades8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spades8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spades9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spades9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spadesA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spadesA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spadesJ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spadesJ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spadesK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spadesK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spadesQ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spadesQ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
